### ISSUE TITLE
"Declared by" link to line number of corresponding mkOption statement directly

### ISSUE THREAD

**Issue by Lesik** [mipmip/home-manager-option-search#11]
This is a great tool! Many thanks for that!

I had an improvement idea. With large Nix declaration files, it would be useful if the "declared by" link would link directly to the option you're currently viewing, as opposed to the declaration file in general.

Example, in the case of this entry:

![Screenshot from 2023-07-28 13-26-39](https://github.com/mipmip/home-manager-option-search/assets/2021487/6f922296-31eb-4a89-a98f-bc8ae28b18af)

Link to

```
https://github.com/nix-community/home-manager/blob/master/modules/misc/gtk.nix#L164
```

and not to

```
https://github.com/nix-community/home-manager/blob/master/modules/misc/gtk.nix
```

**Comment by mipmip** [comment]
Yes, nice improvement indeed. I don't know if this extra paragraph info is available. Will have a look when I have time.
