### ISSUE TITLE
Can't add as a search engine on Firefox

### ISSUE THREAD

**Issue by lo-kiss** [mipmip/home-manager-option-search#12]
On Firefox you add a custom search engine by right clicking the search bar and an option should appear in the menu saying `Add "x"`. In this case it doesn't appear.

How it should look:
![image](https://github.com/mipmip/home-manager-option-search/assets/115636509/62fe9c81-6a59-4d09-a64c-5856854fd49a)

Not really a big deal in the grand scheme of things, but it would fit nicely with the rest of the workflow as the official nixos search website provides two different search engines, packages and options.

![image](https://github.com/mipmip/home-manager-option-search/assets/115636509/ce9ce237-5d27-43af-88cb-f65351db3d63)

**Might be of interest**:
- https://en.wikipedia.org/wiki/OpenSearch

Either way, handy website so thank you!

**Comment by mipmip** [comment]
Thanks. This is a great feature request. I will add this for sure. PR are welcome too.
