### ISSUE TITLE
Search strange behavior with `programs` keyword at the beginning

### ISSUE THREAD

**Issue by woojiq** [mipmip/home-manager-option-search#16]
**MRE**:
1. Search for `programs.fish.shellAliases` - it shows *shellAliases* for _zsh_ and not _fish_.
2. Search for `fish.shellAliases`, - it works correctly.

Also, if you search for `programs.fish`, it won't show all the options available for *fish* (I've tried to change behavior with search options, but that doesn't help much).
As you can see, there are no `fish.shellAliases` (only zsh), `fish.shellAbbrs` and possibly more, but they do exist if I write without `programs.`

![image](https://github.com/mipmip/home-manager-option-search/assets/122799969/95d1a5f4-5ca8-4e66-9ff8-c24eba2713ca)

**Comment by mipmip** [comment]
this seems to be fixed together with #18
