### ISSUE TITLE
Attr set default does not render in Option Search but does in Home Manager Doc

### ISSUE THREAD

**Issue by Elrendio** [mipmip/home-manager-option-search#27]
When going on [Home Manager Option Search](https://mipmip.github.io/home-manager-option-search/?query=xsession.windowManager.i3.config.colors.focused
) the defaults for `xsession.windowManager.i3.config.colors.focused` doesn't render when it does on [Home Manager Doc](https://nix-community.github.io/home-manager/options.xhtml#opt-xsession.windowManager.i3.config.colors.focused) which makes it very hard to guess the attribute set to input.

Thanks 🙏 

Screenshots:
<img width="1512" alt="Screenshot 2024-01-26 at 18 13 06" src="https://github.com/mipmip/home-manager-option-search/assets/14873911/ba5d9655-6117-4c97-93aa-7ce59fcc8f5e">
![image_720](https://github.com/mipmip/home-manager-option-search/assets/14873911/3d1d339a-d34d-4769-8673-958e0b03a8db)

**Comment by mipmip** [comment]
this has been fixed
