### ISSUE TITLE
Certain spaces disappear in package descriptions

### ISSUE THREAD

**Issue by vojta001** [mipmip/home-manager-option-search#33]
Have a look at `programs.feh.keybindings` for example. Any space that is represented by a newline in the original source is missing. 

I suspect `html.gsub!("\n","")` in `scripts/parse_appendix.rb` is at fault. Why is it even there? It is clearly against the HTML spec, as any whitespace is a space and only multiple consecutive spaces shall be skipped.

I believe simply changing the line to `html.gsub!("\n"," ")` (or dropping it entirely) should fix the issue, but I didn't have a chance yet to test it.

**Comment by mipmip** [comment]
should be fixed now
